import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";


// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Mono Font
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata (SEO)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children } : Readonly<{ children: React.ReactNode; }>) 
{
  return (
    <html lang="fr">
      <SessionProvider>
        <body className= {`${geistSans.variable} ${geistMono.variable} antialiased`} >
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
